### ISSUE TITLE
Open/ClosePosition add input param `receiver`

### ISSUE THREAD

**Issue by itsermin** [lyra-finance/lyra-protocol#5]
For easier third party integrations, it would be useful when opening/closing positions, that there is an input parameter address `receiver`.

When opening a position, instead of sending the minted token to msg.sender, it would go to the `receiver` address.
When closing a position, instead of sending collateral to msg.sender, it would go to the `receiver` address.

This makes it easier for third party contracts to handle assets on behalf of the user.

**Comment by 0xdomrom** [comment]
Agree this would be handy but it becomes really confusing when you start thinking about how you handle collateral updates, theres a number of cases here that when mapped out get very ambiguous as to how they should be handled. The approach taken here is to remain unopinionated in how the collateral transfers are handled and allow integrators to handle that as they please.
